version: '2'
services:
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}_nginx
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/ssl:/etc/ssl"
      - "./app:/var/www/html"
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    ports:
      - "${NGINX_PORT}:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - CONTAINER_WEB_ROOT=$CONTAINER_WEB_ROOT
      - PHP_FPM_HANDLER=php:${PHP_FPM_PORT}
    command: /bin/sh -c "envsubst '$$NGINX_HOST,$$CONTAINER_WEB_ROOT,$$PHP_FPM_HANDLER'< /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - php
      - mysqld
    links:
      - php
  php:
    container_name: ${APP_NAME}_php
    volumes:
      - "./app:${CONTAINER_WEB_ROOT}"
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - PHP_FPM_PORT=${PHP_FPM_PORT}
    environment:
      - PHP_FPM_PORT=${PHP_FPM_PORT}
      - PHP_VERSION=${PHP_VERSION}
    ports:
      - 9000:9000
    command: php -S="0.0.0.0:9000" -t="/var/www/html"
  mysqld:
    volumes:
      - "./mysql/data:/usr/share"
      - ./mysql/conf/my.cnf:/etc/my.cnf.d/my.cnf
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    container_name: ${APP_NAME}_mysqld
    command: --default-authentication-plugin=mysql_native_password
    env_file:
        - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}_phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    depends_on:
      - mysqld
