version: '2'
services:
  nginx:
    container_name: demo_nginx
    volumes:
      - ./app:${CONTAINER_WEB_ROOT}
    build:
      context: ./nginx
      args:
        - PHP_FPM_FASTCGI=${PHP_FPM_HOST}:${PHP_FPM_PORT}
        - CONTAINER_WEB_ROOT=${CONTAINER_WEB_ROOT}
        - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_SSL_PORT}:443
    depends_on:
      - php-fpm
      - mysqld
  php-fpm:
    container_name: demo_php
    volumes:
      - ./app:${CONTAINER_WEB_ROOT}
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - PHP_FPM_PORT=${PHP_FPM_PORT}
    environment:
      - PHP_FPM_PORT=${PHP_FPM_PORT}
      - PHP_VERSION=${PHP_VERSION}
    ports:
      - 9000:9000
    command: php -S="0.0.0.0:9000" -t="/var/www/html"
  mysqld:
    volumes:
      - "./mysql/data:/usr/share"
      - ./mysql/conf/my.cnf:/etc/my.cnf.d/my.cnf
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    container_name: demo_mysqld
    command: --default-authentication-plugin=mysql_native_password
    env_file:
        - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: demo_phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    depends_on:
      - mysqld
